######################################################################
# Automatically generated by qmake (2.01a) ven. oct. 25 11:23:51 2013
######################################################################

TEMPLATE = app
TARGET = hybridServer.bin
QT += network
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hybridServer.h
SOURCES += hybridServer.cpp main.cpp
